module BayesianIntegral

using LinearAlgebra
using Random

include("integrate_given_hyperparameters.jl")
include("calibrate_weights.jl")
export gaussian_kernel_hyperparameters
export bayesian_integral_gaussian_exponential, marginal_likelihood_gaussian_derivatives, log_likelihood, calibrate_by_ML_with_SGD
export bayesian_integral_exponential_log_likelihood, train_with_RProp, bayesian_integral_exponential
end
